name: Create PR
description: |
  変更したファイルをコミットし、プルリクエストを作成します。
  プルリクエストのタイトルや本文には、コミットメッセージがそのまま利用されます。
  パーミッションに「contents: write」と「pull-requests: write」を指定する必要があります。
inputs:
  message:
    required: true
    description: コミットメッセージ
outputs:
  branch:
    value: ${{ steps.pr.outputs.branch }}
    description: プルリクエストのブランチ名
runs:
  using: composite
  steps:
    - id: pr
      shell: bash
      env:
        USERNAME: github-actions[bot]
        EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        MESSAGE: ${{ inputs.message }}
        BRANCH: auto/${{ github.run_id }}/${{ github.run_attempt }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "branch=${BRANCH}" >> "${GITHUB_OUTPUT}"
        git config --global user.name "${USERNAME}"
        git config --global user.email "${EMAIL}"
        git swich -c "${BRANCH}"
        git add .
        git commit -m "${MESSAGE}"
        git push origin "${BRANCH}"
        git pr create --head "${BRANCH}" --title "${MESSAGE}" \
          --body "${MESSAGE}"