name: Variables        # ワークフロー名
on: push             # push イベントをトリガー
jobs:               # ジョブの定義
  print:            # ジョブID
    runs-on: ubuntu-latest      # 実行環境
    env:
      PASSWORD: ${{ secrets.PASSWORD }}  # 環境変数の定義
    steps:                      # ステップの定義
        - run: echo "${PASSWORD}"  # 実行するコマンド
        - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"  # 実行するコマンド