name: Intermediate Environment variables         # ワークフロー名
on: 
  push:             # push イベントをトリガー
    branches:       # 対象のブランチを指定
      - main        # 例: main ブランチ
jobs:               # ジョブの定義
  print:            # ジョブID
    runs-on: ubuntu-latest      # 実行環境
    env:
      ACTOR: ${{ github.actor }}  # 環境変数の定義
    steps:                      # ステップの定義
        - run: echo "${ACTOR}"  # 実行するコマンド