name: Literals
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}  # null
          LITERAL_TRUE: ${{ true }}  # true
          LITERAL_FALSE: ${{ false }}  # false
          LITERAL_STRING: ${{ 'string' }}  # string
          LITERAL_NUMBER: ${{ 123 }}  # 123
          LITERAL_ARRAY: ${{ [1, 2, 3] }}  # [1, 2, 3]