name: Release action
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        options: [
          patch
          minor
          major
        ]
        required: true
        description: |
          バージョンを上げるレベルを選択してください。
          `patch` は 1.0.0 -> 1.0.1 のように、最後の数字が上がります。
          `minor` は 1.0.0 -> 1.1.0 のように、真ん中の数字が上がります。
          `major` は 1.0.0 -> 2.0.0 のように、最初の数字が上がります。
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - env:
          USERNAME: github-actions[bot]
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          BUMP_LEVEL: ${{ inputs.bump-level }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"
          version="$(.github/scripts/bump.sh "${BUMP_LEVEL}")"
          gh release create "${version}" --title "${version}" --generate-notes